export const BASE_API_URL = "https://api.steampowered.com"
export const GET_PLAYER_SUMMARIES = "/ISteamUser/GetPlayerSummaries/v2/"
export const GET_FRIEND_LIST = "ISteamUser/GetFriendList/v1"
export const GET_PLAYER_BANS = "ISteamUser/GetPlayerBans/v1"
export const GET_USER_GROUP_LIST = "ISteamUser/GetUserGroupList/v1"
